### ISSUE TITLE
Request: Options to Tweak Album Matching Engine

### ISSUE THREAD

**Issue by RandomNinjaAtk** [Lidarr/Lidarr#779]
**Is your feature request related to a problem? Please describe.**
Would like the opton to make changes to how albums are matched. Currently the matching seems to use a system similar to "Beets" (beets.io), but will match anything with above an 80% accuracy score.

**Describe the solution you'd like**
To be able to adjust matching settings, more like beets.io. Here is my example matching config for beets, which only accepts anything over 96% match but has a bunch of tweaks to ignore incorect information, such as country and etc.

```
match:
    strong_rec_thresh: 0.04
    distance_weights:
        missing_tracks: 10.0
        unmatched_tracks: 10.0
        track_index: 10.0
        track_length: 10.0
        track_id: 10.0
        source: 0
        artist: 1
        album: 3.0
        media: 1
        mediums: 1
        year: 0.5
        country: 0
        label: 0
        catalognum: 0
        albumdisambig: 0
        album_id: 5.0
        tracks: 10.0
        track_title: 3.0
        track_artist: 0.1
    required: year language
    ignored_media: ['Data CD', 'DVD', 'DVD-Video', 'Blu-ray', 'HD-DVD',
                    'VCD', 'SVCD', 'UMD', 'VHS']
    ignored: missing_tracks unmatched_tracks
    preferred:
        countries: ['US']
        media: ['Digital Media|CD']
        original_year: yes
```

**Describe alternatives you've considered**
Not use internal matching system, match using beets and manually import after (non-ideal)

[AB#435](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/435)
